#Window Navigation
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up

#Theme
include ./theme.conf

#Layouts
enabled_layouts splits
map ctrl+shift+h launch --location=hsplit
map ctrl+shift+v launch --location=vsplit
map f7 layout_action rotate


#Window Resizing
map ctrl+shift+left resize_window narrower
map ctrl+shift+right resize_window wider
map ctrl+shift+up resize_window taller
map ctrl+shift+down resize_window shorter 3

#Formatting
font_size 13.5
hide_window_decorations titlebar-only


