# Automatically set the window title
set-window-option -g automatic-rename off

# activity notifications
setw -g monitor-activity on
setw -g visual-activity on

# increase scrollback buffer to 10000
set -g history-limit 10000

#change pane divider style

# Remapping prefix
unbind-key C-b
set-option -g prefix C-s # setting prefix from C-b to C-s
bind-key C-s send-prefix # ensure that we can send Ctrl-s to other apps or the shell
